// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using educacionit.cursowebapi.clase3.Data;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace educacionit.cursowebapi.clase3.Models
{
    public partial class Shipper : IEntity
    {
        [Key]
        [Column("ShipperID")]
        public int Id { get; set; }
        [Required]
        [StringLength(40)]
        public string CompanyName { get; set; }
        [StringLength(24)]
        public string Phone { get; set; }
    }
}