// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace educacionit.cursowebapi.clase3.Models
{
    public partial class Usuario
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [Column("Usuario")]
        [StringLength(10)]
        public string Usuario1 { get; set; }
        [Required]
        [StringLength(10)]
        public string Password { get; set; }
        [StringLength(50)]
        public string Apellido { get; set; }
        [StringLength(50)]
        public string Nombre { get; set; }
        [StringLength(50)]
        public string Email { get; set; }
    }
}